image:
  file: .gitpod.Dockerfile    

vscode:
  extensions:
    - ms-vscode.cpptools@1.1.3:8J7wiDlqJGxnxcM0gJYGEA==
    - redhat.java@0.73.0:zlb1d2d/RWALCADFGFpJMg==
    - vscjava.vscode-java-dependency@0.16.0:wWf+IBtGNvKfRuFRdX+Kjw==
    - vscjava.vscode-java-debug@0.30.0:DaEmYtyUCSxaY5vXQG3CJQ==
    - wpilibsuite.vscode-wpilib@2021.1.2:8vYGNGnTooE+WGwJgAIgZQ==
